'use client'

import ModalProvider from '@/components/ModalProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/providers'
import { StyledEngineProvider } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>
          <ModalProvider>{children}</ModalProvider>
        </StyledEngineProvider>
      </body>
    </html>
  )
}
